# Generated by Django 5.2.6 on 2025-09-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('pickup_addr', models.CharField(max_length=100)),
                ('delivery_addr', models.CharField(max_length=100)),
                ('total_weight', models.FloatField()),
                ('date', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
