# Generated by Django 5.2.6 on 2025-09-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('availablity_status_driver', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('max_capacity', models.CharField(max_length=100)),
                ('cost_per_km', models.CharField(max_length=100)),
                ('current_position', models.FloatField()),
                ('availablity_status_vehicle', models.BooleanField()),
            ],
        ),
    ]
