# Generated by Django 5.2.6 on 2025-09-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_drivers_vehicles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivers',
            old_name='availablity_status_driver',
            new_name='availability_status_driver',
        ),
        migrations.RenameField(
            model_name='vehicles',
            old_name='availablity_status_vehicle',
            new_name='availability_status_vehicle',
        ),
    ]
