# Generated by Django 5.2.6 on 2025-09-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_availablity_status_driver_drivers_availability_status_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='cost_per_km',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='current_position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='max_capacity',
            field=models.FloatField(),
        ),
    ]
