# Generated by Django 5.2.6 on 2025-09-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_vehicles_cost_per_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
